# Generated by Django 5.2.14 on 2026-05-17 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('usage_count', models.IntegerField(default=0)),
                ('confidence_threshold', models.FloatField(default=0.7)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.FloatField(default=0.85)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('document_category', models.CharField(default='Unknown', max_length=100)),
                ('suggested_category', models.CharField(blank=True, max_length=100)),
                ('variant_name', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('ai_confidence_score', models.FloatField(default=0.0)),
                ('user_confirmation_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('corrected', 'Corrected')], default='pending', max_length=20)),
                ('user_corrected_data', models.JSONField(blank=True, default=dict)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('reviewed_data', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('user_confirmed', 'User Confirmed'), ('under_review', 'Under Review'), ('review_approved', 'Review Approved'), ('review_rejected', 'Review Rejected'), ('high_risk_review', 'High Risk Review')], default='pending', max_length=30)),
                ('required_reviewers', models.IntegerField(default=1)),
                ('ai_used', models.BooleanField(default=True)),
                ('encryption_enabled', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('validation_regex', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_level', models.IntegerField(choices=[(0, 'No AI'), (1, 'Light AI'), (2, 'Full AI'), (3, 'Advanced AI')], default=2)),
                ('use_ai_extraction', models.BooleanField(default=True)),
                ('use_ai_classification', models.BooleanField(default=True)),
                ('use_ai_relationship', models.BooleanField(default=False)),
                ('enable_encryption', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='documents.document')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('extraction_rules', models.JSONField(blank=True, default=dict)),
                ('confidence_boost', models.FloatField(default=0.1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentcategory')),
            ],
        ),
    ]
