# Generated by Django 5.2.14 on 2026-05-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='belongs_to',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
