# Generated by Django 5.2.14 on 2026-05-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_document_category_document_extracted_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('usage_count', models.IntegerField(default=0)),
                ('confidence_threshold', models.FloatField(default=0.7)),
            ],
        ),
    ]
