# Generated by Django 5.2.14 on 2026-05-16 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('extraction_rules', models.JSONField(blank=True, default=dict)),
                ('confidence_boost', models.FloatField(default=0.1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentcategory')),
            ],
        ),
    ]
