# Generated by Django 5.2.14 on 2026-05-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='variant_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
