# Generated by Django 5.2.14 on 2026-05-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documentfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='raw_ai_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
