# Generated by Django 5.2.14 on 2026-05-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_raw_ai_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
