# Generated by Django 5.2.14 on 2026-05-17 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_document_document_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='is_verified',
            new_name='encryption_enabled',
        ),
        migrations.RemoveField(
            model_name='document',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='document',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_used',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='user_confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('corrected', 'Corrected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='user_corrected_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.FloatField(default=0.85)),
                ('ai_level', models.IntegerField(choices=[(0, 'No AI'), (1, 'Light AI'), (2, 'Full AI'), (3, 'Advanced AI')], default=2)),
                ('use_ai_extraction', models.BooleanField(default=True)),
                ('use_ai_classification', models.BooleanField(default=True)),
                ('use_ai_relationship', models.BooleanField(default=False)),
                ('enable_encryption', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
